name: zmc.space
description: Live. Die. Repeat.
meta_description: "zmc.space, blogging about things I learn"

aboutPage: true

markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
    extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: rouge

gems: ['jekyll-paginate']
paginate: 20
baseurl: /
domain_name: 'http://zmc.space'
google_analytics: 'UA-71841354-1'
disqus: true
disqus_shortname: 'zmcspace'

# Details for the RSS feed generator
url:            'http://zmc.space'
author:         'Furkan Üzümcü'
authorTwitter:  'furkanzmc'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
